export default function handler(req, res) {
  res.json({
    testimonials: [
      {
        name: "Rbimephis",
        title: "CEO, Xen Insurance",
        text: "I had the pleasure of working with cwmservices on a website design project for our company. He was professional, responsive, and delivered high-quality work that exceeded our expectations. I highly recommend cwmservices for any web development project.",
        image_url: "/rbimemphis.jfif",
      },
      {
        name: "Apiscrypto",
        title: "CEO, Dynasty NFT Games",
        text: "We had the opportunity to collaborate with cwmservices on a react web app project for one of our clients. cwmservices was a great asset to our team, bringing a wealth of knowledge and experience to the table. The quality of work done was good.",
        image_url: "/apiscrypto.png",
      },
      {
        name: "Hamza Javed",
        title: "YouTube Creator",
        text: "I was searching about coding tips and guides on youtube and had suddenly came across CodeWithMasood youtube channel he presents the best online tutorials.I would say Thanks sir for providing information, please make a full course on python.",
        image_url: "/t1.jpg",
      },
      {
        name: "Victoria K",
        title: "VICTORY PUB",
        text: "I was searching about coding tips and guides on youtube and had suddenly came across CodeWithMasood youtube channel he presents the best online tutorials.I would say Keep up the EXCELLENT work and do give plenty of exercises and practical examples Sir!",
        image_url: "/t2.jpg",
      },
      {
        name: "Danish",
        title: "Kustian",
        text: "I was searching about coding tips and guides on youtube and had suddenly came across CodeWithMasood youtube channel he presents the best online tutorials.I would say Out class keep it up bro. I finally got my project completed. Nice Work, keep it up",
        image_url: "/t3.jpg",
      },
    ],
    name: "Full Stack Developer",
    skills: [
      "JavaScript",
      "Node.js",
      "React",
      "React Native",
      "Next.js",
      "HTML5",
      "CSS3",
      "Tailwind CSS",
      "TypeScript",
      "Express.js",
      "MongoDB",
    ],
    experience: "4+ years",
    projects: [
      {
        title: "Full Stack E-commerce Web Application",
        code: "https://github.com/cwmservices/cwmstorefrontend",
        demo: "https://cwmstore.netlify.app",
        image: "/1.png",
        category: "web",
      },
      {
        title: "Chatting Web Application",
        code: "https://github.com/cwmservices/mchat-frontend",
        demo: "https://mchatt.netlify.app",
        image: "/2.png",
        category: "web",
      },
      {
        title: "Xen Insurance Web Application Project",
        code: "https://github.com/cwmservices/xeninsuranceproject",
        demo: "https://xeninsurance.netlify.app",
        image: "/3.jpg",
        category: "web",
      },
      {
        title: "Notes Keeper Web App",
        code: "https://github.com/cwmservices/Notes-Keeper",
        demo: "https://cwmservices.github.io/Notes-Keeper",
        image: "/4.png",
        category: "web",
      },
      {
        title: "Weight Converter Web App",
        code: "https://github.com/cwmservices/Weight-Converter",
        demo: "https://cwmservices.github.io/Weight-Converter",
        image: "/5.png",
        category: "web",
      },
      {
        title: "Currency Converter Web App",
        code: "https://github.com/cwmservices/currency-converter-app",
        demo: "https://cwmservices.github.io/currency-converter-app",
        image: "/6.png",
        category: "web",
      },
      {
        title: "Brick Breaker 2D Game Application",
        code: "https://github.com/cwmservices/Brick-Breaker-Game",
        demo: "https://cwmservices.github.io/Brick-Breaker-Game",
        image: "/7.png",
        category: "web",
      },
      {
        title: "Beautiful Portfolio Website",
        code: "https://github.com/cwmservices/beautifulPortfolioWebsite",
        demo: "https://beautifulportfolioapp.000webhostapp.com",
        image: "/8.jpg",
        category: "web",
      },
      {
        title: "Coffee Shop Mobile Application",
        code: "https://github.com/cwmservices/coffee-shop-app-react-native-firebase-nodejs",
        demo: "https://drive.google.com/file/d/1WD7cx6OuvEmEYFQcZosiXRB4jNGu3H/view?usp=share_link",
        image: "/9.png",
        category: "app",
      },
      {
        title: "Guess The Number Game",
        code: "https://github.com/cwmservices/React-Native-Guess-The-Number-App",
        demo: "https://drive.google.com/file/d/1cebazMZHZ42pYa1breEYSnv65pjqrNgM/view",
        image: "/10.png",
        category: "app",
      },
      {
        title: "TodoList Mobile Application",
        code: "https://github.com/cwmservices/React-Native-ToDoList-App",
        demo: "https://drive.google.com/file/d/1w_anb7sVioJMEyDeKBfaLusDZGLo0YIj/view",
        image: "/11.png",
        category: "app",
      },
      {
        title: "XenInsurance Website Design",
        demo: "https://www.figma.com/proto/k865fFn4GwHab4HitHZ176/Xen-Insurance?node-id=0%3A1&scaling=min-zoom&page-id=0%3A1",
        code: "https://github.com/cwmservices/xeninsuranceproject",
        image: "/12.png",
        category: "design",
      },
    ],
  });
}
